spring:
  datasource:
    username: root
    password: Yutong@2802
    url: jdbc:mysql://localhost:3306/movie
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: posters/